# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbfd20d2bbe255421b0b62019b1db73577d5cc09a85cccbf2fed03ca993641e6215614f83abd965d91b27a34ce68b186d1f66b28d323cd79ba29f071cf4067ab

test:
  secret_key_base: f773d82187b8769e0f952a09c654f7345f684d73f0bdc26fdb9c346dc8eba3dd68f84fbf124e513c64565e24b3daa26c45ae24e0725131dcd08d1838de837f72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
